// ── Finance suite: accounts, debts, budget, goals, statements, PSLF ───────────
import { useState, useEffect } from "react";
import { store } from "./store";
import { CATS, ACCT_TYPES, DEBT_TYPES, DAYS, GOLD, fmt, calcMortgage, calcPayoff, billPaid } from "./constants";
import { Ring, Bar } from "./shared";

// ── ACCOUNT ROW (top-level — must not be inside AccountsTab) ─────────────────
function AcctRow({a,editing,setEditing,update,save,accounts,S}){
  return(<div style={{...S.card,marginBottom:8}}>{editing===a.id?<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(120px,1fr))",gap:8,alignItems:"flex-end"}}><div><div style={S.label}>Name</div><input style={S.input} value={a.name} onChange={e=>update(a.id,"name",e.target.value)}/></div><div><div style={S.label}>Balance</div><input style={S.input} type="number" value={a.balance} onChange={e=>update(a.id,"balance",e.target.value)}/></div><div><div style={S.label}>APY %</div><input style={S.input} type="number" value={a.apy||0} onChange={e=>update(a.id,"apy",e.target.value)}/></div><div><div style={S.label}>Contrib/mo</div><input style={S.input} type="number" value={a.monthlyContrib||0} onChange={e=>update(a.id,"monthlyContrib",e.target.value)}/></div><div><div style={S.label}>Institution</div><input style={S.input} value={a.institution} onChange={e=>update(a.id,"institution",e.target.value)}/></div><button style={{...S.btn(),marginTop:20}} onClick={()=>setEditing(null)}>Done</button></div>:<div style={{...S.row,flexWrap:"wrap",gap:8}}><div style={{display:"flex",gap:10,alignItems:"center"}}><div style={{...S.tag(a.type==="TSP"||a.type==="Roth IRA"||a.type==="401k"?"#9C27B0":a.type==="HYSA"||a.type==="Savings"?"#4CAF50":GOLD)}}>{a.type}</div><div><div style={{fontSize:14,color:S.T.text}}>{a.name}<span style={{fontSize:11,color:S.T.sub}}> · {a.institution}</span></div>{a.apy>0&&<div style={{fontSize:11,color:"#4CAF50"}}>{a.apy}% APY</div>}{a.monthlyContrib>0&&<div style={{fontSize:11,color:"#9C27B0"}}>{fmt(a.monthlyContrib)}/mo</div>}</div></div><div style={{display:"flex",gap:8,alignItems:"center"}}><div style={{fontSize:20,color:GOLD,fontFamily:"monospace",fontWeight:"bold"}}>{fmt(a.balance)}</div><button style={S.btnGhost} onClick={()=>setEditing(a.id)}>Edit</button><button style={S.btnDanger} onClick={()=>save(accounts.filter(x=>x.id!==a.id))}>X</button></div></div>}</div>);
}

function AccountsTab({accounts,setAccounts,profile,S}){
  const blank={name:"",owner:"me",type:"Checking",balance:"",institution:"",apy:"",monthlyContrib:""};
  const [form,setForm]=useState(blank),[editing,setEditing]=useState(null);
  const save=u=>{setAccounts(u);store.save("fp2:accounts",u);};
  const add=()=>{if(!form.name||!form.balance)return;save([...accounts,{...form,id:Date.now(),balance:+form.balance,apy:+form.apy||0,monthlyContrib:+form.monthlyContrib||0}]);setForm(blank);};
  const update=(id,f,v)=>save(accounts.map(a=>a.id===id?{...a,[f]:f==="name"||f==="institution"||f==="owner"||f==="type"?v:+v}:a));
  const myA=accounts.filter(a=>a.owner==="me"),fA=accounts.filter(a=>a.owner==="fiance");
  const rowProps={editing,setEditing,update,save,accounts,S};
  return(<><div style={S.grid2}><div><div style={{...S.h2,...S.row}}><span>{profile.myName}'s Accounts</span><span style={{color:GOLD,fontFamily:"monospace"}}>{fmt(myA.reduce((s,a)=>s+a.balance,0))}</span></div>{myA.map(a=><AcctRow key={a.id} a={a} {...rowProps}/>)}</div><div><div style={{...S.h2,...S.row}}><span>{profile.fianceName}'s Accounts</span><span style={{color:GOLD,fontFamily:"monospace"}}>{fmt(fA.reduce((s,a)=>s+a.balance,0))}</span></div>{fA.map(a=><AcctRow key={a.id} a={a} {...rowProps}/>)}</div></div><div style={S.card}><div style={S.h2}>Add Account</div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(130px,1fr))",gap:10,alignItems:"flex-end"}}><div><div style={S.label}>Name</div><input style={S.input} placeholder="Main Checking" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></div><div><div style={S.label}>Type</div><select style={S.select} value={form.type} onChange={e=>setForm({...form,type:e.target.value})}>{ACCT_TYPES.map(t=><option key={t}>{t}</option>)}</select></div><div><div style={S.label}>Owner</div><select style={S.select} value={form.owner} onChange={e=>setForm({...form,owner:e.target.value})}><option value="me">{profile.myName}</option><option value="fiance">{profile.fianceName}</option></select></div><div><div style={S.label}>Balance</div><input style={S.input} type="number" placeholder="0" value={form.balance} onChange={e=>setForm({...form,balance:e.target.value})}/></div><div><div style={S.label}>APY %</div><input style={S.input} type="number" placeholder="0" value={form.apy} onChange={e=>setForm({...form,apy:e.target.value})}/></div><div><div style={S.label}>Institution</div><input style={S.input} placeholder="Ally" value={form.institution} onChange={e=>setForm({...form,institution:e.target.value})}/></div><button style={S.btn()} onClick={add}>Add</button></div></div></>);
}

function DebtsTab({debts,setDebts,profile,S}){
  const blank={name:"",type:"Credit Card",balance:"",rate:"",minPayment:"",owner:"me"};
  const [form,setForm]=useState(blank),[editing,setEditing]=useState(null);
  const save=u=>{setDebts(u);store.save("fp2:debts",u);};
  const add=()=>{if(!form.name||!form.balance)return;save([...debts,{...form,id:Date.now(),balance:+form.balance,rate:+form.rate||0,minPayment:+form.minPayment||0}]);setForm(blank);};
  const update=(id,f,v)=>save(debts.map(d=>d.id===id?{...d,[f]:f==="name"||f==="type"||f==="owner"?v:+v}:d));
  const total=debts.reduce((s,d)=>s+d.balance,0),totalMin=debts.reduce((s,d)=>s+d.minPayment,0);
  return(<><div style={S.grid3}>{[{l:"Total Debt",v:fmt(total),c:"#f44336"},{l:"Min Payments",v:fmt(totalMin)+"/mo",c:"#FF9800"},{l:"Avg APR",v:(debts.filter(d=>d.rate>0).reduce((s,d)=>s+d.rate,0)/Math.max(debts.filter(d=>d.rate>0).length,1)).toFixed(1)+"%",c:"#FF9800"}].map((k,i)=><div key={i} style={{...S.card,borderTop:`3px solid ${k.c}`,marginBottom:0}}><div style={S.label}>{k.l}</div><div style={{fontSize:20,color:k.c,fontFamily:"monospace",fontWeight:"bold"}}>{k.v}</div></div>)}</div>
    <div style={{marginTop:14}}>{debts.map(d=>{const tc=d.type==="Credit Card"?"#f44336":d.type==="Student Loan"?"#2196F3":d.type==="Auto"?"#FF9800":"#888";return <div key={d.id} style={{...S.card,marginBottom:8,borderLeft:`3px solid ${tc}`}}>{editing===d.id?<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(120px,1fr))",gap:8,alignItems:"flex-end"}}><div><div style={S.label}>Name</div><input style={S.input} value={d.name} onChange={e=>update(d.id,"name",e.target.value)}/></div><div><div style={S.label}>Balance</div><input style={S.input} type="number" value={d.balance} onChange={e=>update(d.id,"balance",e.target.value)}/></div><div><div style={S.label}>APR %</div><input style={S.input} type="number" value={d.rate} onChange={e=>update(d.id,"rate",e.target.value)}/></div><div><div style={S.label}>Min Payment</div><input style={S.input} type="number" value={d.minPayment} onChange={e=>update(d.id,"minPayment",e.target.value)}/></div><div><div style={S.label}>Type</div><select style={S.select} value={d.type} onChange={e=>update(d.id,"type",e.target.value)}>{DEBT_TYPES.map(t=><option key={t}>{t}</option>)}</select></div><button style={{...S.btn(),marginTop:20}} onClick={()=>setEditing(null)}>✓</button></div>:<div style={{...S.row,flexWrap:"wrap",gap:8}}><div><div style={{display:"flex",gap:8,alignItems:"center",marginBottom:4,flexWrap:"wrap"}}><span style={{fontSize:14,color:S.T.text}}>{d.name}</span><span style={S.tag(tc)}>{d.type}</span>{d.pslf&&<span style={S.tag("#4CAF50")}>PSLF</span>}</div><div style={{display:"flex",gap:12,fontSize:12,color:S.T.sub}}>{d.rate>0&&<span>{d.rate}% APR</span>}<span>Min: {fmt(d.minPayment)}/mo</span>{d.pslf&&<span style={{color:"#4CAF50"}}>DO NOT pay extra</span>}</div></div><div style={{display:"flex",gap:8,alignItems:"center"}}><span style={{fontSize:20,color:tc,fontFamily:"monospace",fontWeight:"bold"}}>{fmt(d.balance)}</span><button style={S.btnGhost} onClick={()=>setEditing(d.id)}>Edit</button><button style={S.btnDanger} onClick={()=>save(debts.filter(x=>x.id!==d.id))}>✕</button></div></div>}</div>;})}
    </div><div style={S.card}><div style={S.h2}>Add Debt</div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(120px,1fr))",gap:10,alignItems:"flex-end"}}><div><div style={S.label}>Name</div><input style={S.input} placeholder="Chase Sapphire" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></div><div><div style={S.label}>Type</div><select style={S.select} value={form.type} onChange={e=>setForm({...form,type:e.target.value})}>{DEBT_TYPES.map(t=><option key={t}>{t}</option>)}</select></div><div><div style={S.label}>Balance</div><input style={S.input} type="number" placeholder="0" value={form.balance} onChange={e=>setForm({...form,balance:e.target.value})}/></div><div><div style={S.label}>APR %</div><input style={S.input} type="number" placeholder="0" value={form.rate} onChange={e=>setForm({...form,rate:e.target.value})}/></div><div><div style={S.label}>Min Payment</div><input style={S.input} type="number" placeholder="0" value={form.minPayment} onChange={e=>setForm({...form,minPayment:e.target.value})}/></div><button style={S.btn()} onClick={add}>Add</button></div></div></>);
}

function BudgetTab({expenses,setExpenses,transactions,takeHome,slPayment,S}){
  const [editCat,setEditCat]=useState(null),[newCat,setNewCat]=useState(""),[newItem,setNewItem]=useState({catId:null,name:"",amount:"",due:""});
  const save=u=>{setExpenses(u);store.save("fp2:expenses",u);};
  const total=expenses.reduce((s,c)=>s+c.items.reduce((ss,i)=>ss+i.amount,0),0);
  const now=new Date(),mo=now.getMonth(),yr=now.getFullYear();
  const mTxns=transactions.filter(t=>{const d=new Date(t.date);return d.getMonth()===mo&&d.getFullYear()===yr&&t.amount<0;});
  const actuals={};CATS.forEach(c=>{actuals[c]=mTxns.filter(t=>t.category===c).reduce((s,t)=>s+Math.abs(t.amount),0);});
  const addCat=()=>{if(!newCat)return;save([...expenses,{id:Date.now(),category:newCat,items:[]}]);setNewCat("");};
  const delCat=id=>save(expenses.filter(c=>c.id!==id));
  const addItem=()=>{if(!newItem.catId||!newItem.name||!newItem.amount)return;save(expenses.map(c=>c.id===newItem.catId?{...c,items:[...c.items,{id:Date.now(),name:newItem.name,amount:+newItem.amount,due:+newItem.due||0}]}:c));setNewItem({catId:newItem.catId,name:"",amount:"",due:""});};
  const delItem=(cId,iId)=>save(expenses.map(c=>c.id===cId?{...c,items:c.items.filter(i=>i.id!==iId)}:c));
  const updateItem=(cId,iId,f,v)=>save(expenses.map(c=>c.id===cId?{...c,items:c.items.map(i=>i.id===iId?{...i,[f]:f==="name"?v:+v}:i)}:c));
  return(<><div style={S.grid3}>{[{l:"Total Budgeted",v:fmt(total),c:GOLD},{l:"Take-Home",v:fmt(takeHome),c:"#4CAF50"},{l:"Surplus",v:fmt(takeHome-total-slPayment),c:(takeHome-total-slPayment)>0?"#4CAF50":"#f44336"}].map((k,i)=><div key={i} style={{...S.card,borderTop:`3px solid ${k.c}`,marginBottom:0}}><div style={S.label}>{k.l}</div><div style={{fontSize:20,color:k.c,fontFamily:"monospace",fontWeight:"bold"}}>{k.v}</div></div>)}</div>
    <div style={{marginTop:14}}>{expenses.map(cat=>{const ct=cat.items.reduce((s,i)=>s+i.amount,0),act=actuals[cat.category]||0,over=act>ct&&ct>0;return <div key={cat.id} style={S.card}><div style={{...S.row,marginBottom:10,flexWrap:"wrap",gap:8}}><div style={{display:"flex",gap:8,alignItems:"center"}}><button style={{...S.btnGhost,padding:"3px 8px",fontSize:12}} onClick={()=>setEditCat(editCat===cat.id?null:cat.id)}>{editCat===cat.id?"▲":"▼"}</button><span style={{fontSize:14,color:S.T.text}}>{cat.category}</span>{act>0&&<span style={S.tag(over?"#f44336":"#4CAF50")}>{over?"Over":"Actual"}: {fmt(act)}</span>}</div><div style={{display:"flex",gap:8,alignItems:"center"}}><span style={{color:over?"#f44336":GOLD,fontFamily:"monospace",fontWeight:"bold"}}>{fmt(ct)}/mo</span><button style={S.btnDanger} onClick={()=>delCat(cat.id)}>✕</button></div></div>{ct>0&&<Bar value={act} max={ct} color={over?"#f44336":"#4CAF50"}/>}{editCat===cat.id&&<div style={{marginTop:12}}>{cat.items.map(item=><div key={item.id} style={{...S.row,padding:"6px 0",borderBottom:`1px solid #1a1a0f`,flexWrap:"wrap",gap:8}}><div style={{display:"flex",gap:8,alignItems:"center",flex:1}}><input style={{...S.input,maxWidth:180}} value={item.name} onChange={e=>updateItem(cat.id,item.id,"name",e.target.value)}/><input style={{...S.input,maxWidth:90}} type="number" value={item.amount} onChange={e=>updateItem(cat.id,item.id,"amount",e.target.value)}/></div><button style={S.btnDanger} onClick={()=>delItem(cat.id,item.id)}>✕</button></div>)}<div style={{display:"flex",gap:8,marginTop:10,flexWrap:"wrap",alignItems:"flex-end"}}><input style={{...S.input,maxWidth:180}} placeholder="Item name" value={newItem.catId===cat.id?newItem.name:""} onChange={e=>setNewItem({...newItem,catId:cat.id,name:e.target.value})}/><input style={{...S.input,maxWidth:90}} type="number" placeholder="Amount" value={newItem.catId===cat.id?newItem.amount:""} onChange={e=>setNewItem({...newItem,catId:cat.id,amount:e.target.value})}/><button style={S.btn()} onClick={addItem}>+ Add</button></div></div>}</div>;})}
    </div><div style={S.card}><div style={S.h2}>Add Category</div><div style={{display:"flex",gap:8,flexWrap:"wrap"}}><input style={{...S.input,maxWidth:220}} placeholder="Category name" value={newCat} onChange={e=>setNewCat(e.target.value)}/><button style={S.btn()} onClick={addCat}>Add</button></div></div></>);
}

function GoalsTab({goals,setGoals,S}){
  const blank={name:"",icon:"🎯",target:"",saved:"",date:"",color:GOLD};
  const [form,setForm]=useState(blank),[editing,setEditing]=useState(null);
  const save=u=>{setGoals(u);store.save("fp2:goals",u);};
  const add=()=>{if(!form.name||!form.target)return;save([...goals,{...form,id:Date.now(),target:+form.target,saved:+form.saved||0}]);setForm(blank);};
  const update=(id,f,v)=>save(goals.map(g=>g.id===id?{...g,[f]:f==="name"||f==="icon"||f==="color"||f==="date"?v:+v}:g));
  const COLORS=[GOLD,"#4CAF50","#2196F3","#E91E63","#9C27B0","#FF9800","#f44336","#00BCD4"];
  const ICONS=["🏡","🛡","💍","✈️","🌅","🚗","🎓","💰","🏖","🎯"];
  return(<><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(260px,1fr))",gap:14,marginBottom:14}}>{goals.map(g=>{const p=Math.min(g.saved/g.target*100,100),rem=g.target-g.saved,due=new Date(g.date),mo=Math.max(1,Math.round((due-new Date())/(864e5*30)));return(<div key={g.id} style={{...S.card,borderTop:`3px solid ${g.color}`,marginBottom:0}}>{editing===g.id?<div><div style={{display:"flex",gap:6,flexWrap:"wrap",marginBottom:8}}>{ICONS.map(ic=><button key={ic} style={{background:g.icon===ic?g.color+"33":"transparent",border:`1px solid ${g.icon===ic?g.color:S.T.border}`,borderRadius:4,padding:"3px 7px",cursor:"pointer",fontSize:15}} onClick={()=>update(g.id,"icon",ic)}>{ic}</button>)}</div><input style={{...S.input,marginBottom:8}} value={g.name} onChange={e=>update(g.id,"name",e.target.value)}/><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8,marginBottom:8}}><div><div style={S.label}>Target</div><input style={S.input} type="number" value={g.target} onChange={e=>update(g.id,"target",e.target.value)}/></div><div><div style={S.label}>Saved</div><input style={S.input} type="number" value={g.saved} onChange={e=>update(g.id,"saved",e.target.value)}/></div><div><div style={S.label}>Date</div><input style={S.input} type="date" value={g.date} onChange={e=>update(g.id,"date",e.target.value)}/></div><div><div style={S.label}>Color</div><div style={{display:"flex",gap:4,flexWrap:"wrap",marginTop:4}}>{COLORS.map(c=><button key={c} style={{width:20,height:20,borderRadius:"50%",background:c,border:g.color===c?"2px solid #fff":"2px solid transparent",cursor:"pointer"}} onClick={()=>update(g.id,"color",c)}/>)}</div></div></div><button style={{...S.btn(),width:"100%"}} onClick={()=>setEditing(null)}>Done</button></div>:<><div style={{...S.row,marginBottom:8}}><div style={{fontSize:26}}>{g.icon}</div><div style={{display:"flex",gap:6}}><button style={S.btnGhost} onClick={()=>setEditing(g.id)}>Edit</button><button style={S.btnDanger} onClick={()=>save(goals.filter(x=>x.id!==g.id))}>X</button></div></div><div style={{fontSize:15,color:S.T.text,marginBottom:4}}>{g.name}</div><div style={{...S.row,marginBottom:6}}><span style={{color:g.color,fontFamily:"monospace",fontSize:18,fontWeight:"bold"}}>{fmt(g.saved)}</span><span style={{color:S.T.sub,fontFamily:"monospace"}}>{fmt(g.target)}</span></div><Bar value={g.saved} max={g.target} color={g.color} height={8}/><div style={{...S.row,marginTop:8,fontSize:12,color:S.T.sub}}><span>{p.toFixed(0)}% done</span><span>{fmt(rem)} to go</span></div>{g.date&&<div style={{fontSize:11,color:S.T.sub,marginTop:4}}>Target: {g.date} ({mo} mo)</div>}</> }</div>);})}</div>
    <div style={S.card}><div style={S.h2}>Add Goal</div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(140px,1fr))",gap:10,alignItems:"flex-end"}}><div><div style={S.label}>Goal Name</div><input style={S.input} placeholder="e.g. Honeymoon Fund" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></div><div><div style={S.label}>Target</div><input style={S.input} type="number" placeholder="10000" value={form.target} onChange={e=>setForm({...form,target:e.target.value})}/></div><div><div style={S.label}>Saved</div><input style={S.input} type="number" placeholder="0" value={form.saved} onChange={e=>setForm({...form,saved:e.target.value})}/></div><div><div style={S.label}>Target Date</div><input style={S.input} type="date" value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/></div><button style={S.btn()} onClick={add}>Add</button></div></div></>);
}

function StatementsTab({transactions,setTransactions,handleUpload,uploadLoading,reviewTxns,setReviewTxns,confirmTxns,fileRef,S}){
  const [sel,setSel]=useState([]),[catE,setCatE]=useState({});
  useEffect(()=>{if(reviewTxns)setSel(reviewTxns.map(t=>t.id));},[reviewTxns]);
  const toggle=id=>setSel(s=>s.includes(id)?s.filter(x=>x!==id):[...s,id]);
  const confirm=()=>{confirmTxns(reviewTxns.map(t=>({...t,category:catE[t.id]||t.category})).filter(t=>sel.includes(t.id)));setSel([]);setCatE({});};
  const spend=transactions.filter(t=>t.amount<0).reduce((s,t)=>s+Math.abs(t.amount),0);
  const income=transactions.filter(t=>t.amount>0).reduce((s,t)=>s+t.amount,0);
  const byCat={};transactions.filter(t=>t.amount<0).forEach(t=>{byCat[t.category]=(byCat[t.category]||0)+Math.abs(t.amount);});
  return(<><div style={S.card}><div style={S.h2}>Upload Statement</div><div style={{display:"flex",gap:14,alignItems:"center",flexWrap:"wrap"}}><p style={{color:S.T.sub,fontSize:13,margin:0,flex:1}}>Upload a bank or credit card statement (PDF or CSV). AI reads it, categorizes transactions, and shows a review screen before saving.</p><div><input ref={fileRef} type="file" accept=".pdf,.csv,.txt" onChange={handleUpload} style={{display:"none"}}/><button style={{...S.btn(),padding:"12px 24px"}} onClick={()=>fileRef.current?.click()} disabled={uploadLoading}>{uploadLoading?"Processing...":"Choose File"}</button></div></div></div>
    {reviewTxns&&<div style={S.card}><div style={{...S.h2,...S.row,flexWrap:"wrap",gap:8}}><span>Review ({reviewTxns.length} found)</span><div style={{display:"flex",gap:8}}><button style={S.btnGhost} onClick={()=>{setReviewTxns(null);setSel([]);setCatE({});}}>Cancel</button><button style={S.btn()} onClick={confirm}>Confirm {sel.length}</button></div></div><div style={{maxHeight:360,overflowY:"auto"}}>{reviewTxns.map(t=><div key={t.id} style={{...S.row,padding:"7px 0",borderBottom:`1px solid #1a1a0f`,gap:8,opacity:sel.includes(t.id)?1:0.4,flexWrap:"wrap"}}><input type="checkbox" checked={sel.includes(t.id)} onChange={()=>toggle(t.id)} style={{accentColor:GOLD}}/><div style={{flex:1}}><div style={{fontSize:13,color:S.T.text}}>{t.description}</div><div style={{fontSize:11,color:S.T.sub}}>{t.date}</div></div><select style={{...S.select,maxWidth:130,fontSize:11,padding:"4px 8px"}} value={catE[t.id]||t.category} onChange={e=>setCatE({...catE,[t.id]:e.target.value})}>{CATS.map(c=><option key={c}>{c}</option>)}</select><span style={{color:t.amount<0?"#f44336":"#4CAF50",fontFamily:"monospace",fontWeight:"bold",minWidth:70,textAlign:"right"}}>{t.amount<0?"−":"+"}{fmt(Math.abs(t.amount))}</span></div>)}</div></div>}
    {transactions.length>0&&<><div style={S.grid3}>{[{l:"Imported",v:`${transactions.length} txns`,c:GOLD},{l:"Spending",v:fmt(spend),c:"#f44336"},{l:"Income",v:fmt(income),c:"#4CAF50"}].map((k,i)=><div key={i} style={{...S.card,marginBottom:0,borderTop:`3px solid ${k.c}`}}><div style={S.label}>{k.l}</div><div style={{fontSize:18,fontFamily:"monospace",color:k.c,fontWeight:"bold"}}>{k.v}</div></div>)}</div><div style={{...S.card,marginTop:14}}><div style={S.h2}>Spending by Category</div>{Object.entries(byCat).sort((a,b)=>b[1]-a[1]).map(([cat,amt])=><div key={cat} style={{marginBottom:10}}><div style={{...S.row,marginBottom:4}}><span style={{fontSize:13,color:S.T.sub}}>{cat}</span><span style={{fontFamily:"monospace",color:GOLD}}>{fmt(amt)}</span></div><Bar value={amt} max={Math.max(...Object.values(byCat))} color={GOLD}/></div>)}</div><div style={S.card}><div style={S.h2}>Transaction History</div><div style={{maxHeight:320,overflowY:"auto"}}>{[...transactions].reverse().map(t=><div key={t.id} style={{...S.row,padding:"6px 0",borderBottom:`1px solid #1a1a0f`,flexWrap:"wrap",gap:8}}><div><div style={{fontSize:13,color:S.T.text}}>{t.description}</div><div style={{fontSize:11,color:S.T.sub}}>{t.date} · <span style={S.tag("#888")}>{t.category}</span></div></div><span style={{color:t.amount<0?"#f44336":"#4CAF50",fontFamily:"monospace"}}>{t.amount<0?"−":"+"}{fmt(Math.abs(t.amount))}</span></div>)}</div></div></>}
  </>);
}

function ScenariosTab({scenario,setScenario,debts,profile,combinedLiquid,totalCC,mortgageRate,homePrice,slPayment,S}){
  const sDown=homePrice*(scenario.downPct/100),sLoan=homePrice-sDown,sMort=calcMortgage(sLoan,mortgageRate);
  const sPMI=scenario.downPct<20?(sLoan*0.008)/12:0,sTotal=sMort+sPMI+slPayment+300;
  const sInc=(profile.myIncome+profile.fIncome+scenario.incomeBoost)/12;
  const sDTI=(sTotal/(sInc*0.65))*100,sCush=combinedLiquid+scenario.extraSavings-totalCC-sDown-homePrice*0.03;
  const cc=debts.filter(d=>d.type==="Credit Card");
  return(<><div style={{...S.alert("#2196F3"),marginBottom:14}}><span style={{color:"#2196F3",fontWeight:"bold"}}>Scenario Lab — </span><span style={{color:S.T.sub,fontSize:13}}>Adjust sliders to model scenarios. Nothing here changes your real data.</span></div>
    <div style={S.grid2}><div style={S.card}><div style={S.h2}>Adjust the Levers</div>{[{label:"Extra CC Payment/Month",key:"extraPayment",min:0,max:3000,step:50,fmt:fmt,color:GOLD},{label:"Annual Income Boost",key:"incomeBoost",min:0,max:60000,step:1000,fmt:fmt,color:"#4CAF50"},{label:"Down Payment %",key:"downPct",min:5,max:30,step:1,fmt:v=>v+"%",color:scenario.downPct>=20?"#4CAF50":"#FF9800"},{label:"Extra Savings Added",key:"extraSavings",min:0,max:60000,step:1000,fmt:fmt,color:"#9C27B0"}].map(sl=><div key={sl.key} style={{marginBottom:18}}><div style={{...S.row,marginBottom:6}}><div style={S.label}>{sl.label}</div><div style={{color:sl.color,fontFamily:"monospace",fontWeight:"bold"}}>{sl.fmt(scenario[sl.key])}</div></div><input type="range" min={sl.min} max={sl.max} step={sl.step} value={scenario[sl.key]} onChange={e=>setScenario({...scenario,[sl.key]:+e.target.value})} style={{width:"100%",accentColor:sl.color}}/></div>)}</div>
    <div><div style={S.card}><div style={S.h2}>Scenario Results</div>{[{l:"Down Payment",v:fmt(sDown),c:GOLD},{l:"PMI",v:sPMI>0?fmt(sPMI)+"/mo":"$0 — None ✓",c:sPMI>0?"#FF9800":"#4CAF50"},{l:"Monthly Mortgage",v:fmt(sMort),c:S.T.text},{l:"Post-Close Cushion",v:fmt(sCush),c:sCush>15000?"#4CAF50":sCush>5000?"#FF9800":"#f44336"},{l:"DTI",v:sDTI.toFixed(1)+"%",c:sDTI<36?"#4CAF50":sDTI<43?"#FF9800":"#f44336"}].map((r,i)=><div key={i} style={{...S.row,padding:"7px 0",borderBottom:`1px solid #1a1a0f`}}><span style={{fontSize:13,color:S.T.sub}}>{r.l}</span><span style={{color:r.c,fontFamily:"monospace",fontWeight:"bold"}}>{r.v}</span></div>)}</div>
    <div style={S.card}><div style={S.h2}>CC Payoff with Extra Payments</div>{cc.map(d=>{const base=calcPayoff(d.balance,d.rate,d.minPayment),extra=calcPayoff(d.balance,d.rate,d.minPayment+scenario.extraPayment/Math.max(cc.length,1)),saved=base-extra;return <div key={d.id} style={{marginBottom:10}}><div style={{...S.row,marginBottom:4,fontSize:13}}><span style={{color:S.T.sub}}>{d.name}</span><span style={{color:saved>0?"#4CAF50":GOLD,fontFamily:"monospace"}}>{base>=999?"∞":base}mo → {extra>=999?"∞":extra}mo{saved>0&&<span style={{color:"#4CAF50"}}> (−{saved}mo)</span>}</span></div><Bar value={Math.max(0,saved)} max={Math.max(base,1)} color="#4CAF50"/></div>;})}
    </div></div></div></>);
}

function PslfTab({pslf,setPslf,debts,S}){
  const upd=(f,v)=>{const n={...pslf,[f]:v};setPslf(n);store.save("fp2:pslf",n);};
  const sl=debts.find(d=>d.pslf),rem=120-pslf.qualifyingPayments;
  const checklist=[{id:"idr",label:"Enrolled in IDR plan",detail:"SAVE, PAYE, IBR, or ICR"},{id:"emp",label:"Full-time qualifying employer",detail:"Federal, state, local, tribal, or eligible nonprofit"},{id:"ecf",label:"Employment Certification submitted this year",detail:"Submit annually at StudentAid.gov"},{id:"pay",label:"Making on-time qualifying payments",detail:"Every payment must be on-time"},{id:"cnt",label:"Verified payment count at StudentAid.gov",detail:"Log in and confirm"},{id:"loans",label:"Only DIRECT loans",detail:"Not FFEL or Perkins"},{id:"stay",label:"Not leaving federal employment within 24 months",detail:"Leaving resets PSLF"},{id:"nox",label:"NOT making extra student loan payments",detail:"Extra payments waste money on PSLF track"}];
  const [checks,setChecks]=useState(pslf.checks||{});
  const toggleCheck=id=>{const n={...checks,[id]:!checks[id]};setChecks(n);upd("checks",n);};
  const allGood=checklist.every(c=>checks[c.id]);
  return(<><div style={{...S.alert(allGood?"#4CAF50":"#FF9800"),marginBottom:14}}><span style={{color:allGood?"#4CAF50":"#FF9800",fontWeight:"bold"}}>{allGood?"✓ PSLF ON TRACK":"REVIEW CHECKLIST"} — </span><span style={{color:S.T.sub,fontSize:13}}>{pslf.qualifyingPayments} payments · {rem} remaining · {pslf.pslfMonths||24} months to forgiveness of {sl?fmt(sl.balance):"$120,000+"}</span></div>
    <div style={S.grid2}><div style={S.card}><div style={S.h2}>PSLF Status</div>{[{l:"Qualifying Payments",k:"qualifyingPayments",t:"number"},{l:"Total Required",k:"totalPayments",t:"number"},{l:"Months to Forgiveness",k:"pslfMonths",t:"number"},{l:"Employer",k:"employer",t:"text"},{l:"IDR Plan",k:"idrPlan",t:"text"},{l:"Next Cert. Due",k:"certDue",t:"date"}].map(f=><div key={f.k} style={{marginBottom:10}}><div style={S.label}>{f.l}</div><input style={S.input} type={f.t} value={pslf[f.k]||""} onChange={e=>upd(f.k,f.t==="number"?+e.target.value:e.target.value)}/></div>)}<Bar value={pslf.qualifyingPayments} max={pslf.totalPayments} color="#2196F3" height={10}/><div style={{fontSize:11,color:S.T.sub,marginTop:4}}>{((pslf.qualifyingPayments/pslf.totalPayments)*100).toFixed(0)}% complete</div></div>
    <div style={S.card}><div style={S.h2}>Protection Checklist</div>{checklist.map(item=><div key={item.id} style={{display:"flex",gap:10,padding:"8px 0",borderBottom:`1px solid ${S.T.border}`,cursor:"pointer"}} onClick={()=>toggleCheck(item.id)}><div style={{width:18,height:18,borderRadius:4,border:`2px solid ${checks[item.id]?"#4CAF50":S.T.border}`,background:checks[item.id]?"#4CAF50":"transparent",flexShrink:0,display:"flex",alignItems:"center",justifyContent:"center",marginTop:2}}>{checks[item.id]&&<span style={{color:"#0d0d08",fontSize:12,fontWeight:"bold"}}>✓</span>}</div><div><div style={{fontSize:13,color:checks[item.id]?"#4CAF50":S.T.text}}>{item.label}</div><div style={{fontSize:11,color:S.T.sub}}>{item.detail}</div></div></div>)}</div></div>
    <div style={S.card}><div style={S.h2}>Notes</div><textarea style={{...S.input,height:80,resize:"vertical"}} placeholder="Track anything important about your PSLF status..." value={pslf.notes||""} onChange={e=>upd("notes",e.target.value)}/></div></>);
}

function DashboardTab({profile,accounts,debts,goals,expenses,transactions,totalAssets,totalDebtAmt,netWorth,combinedLiquid,totalCC,cushion,dti,mortgageRate,monthlyMortgage,loanAmt,surplus,takeHome,totalExpenses,slPayment,downNeeded,closing,homePrice,setTab,bills,mealPlan,mealSuggestions,shopRequests,S}){
  const ccProg=Math.max(0,(30000-totalCC)/30000*100),pslfProg=Math.max(0,(36-profile.pslfMonths)/36*100);
  const savProg=Math.min(combinedLiquid/(downNeeded+closing+totalCC)*100,100),scoreProg=(profile.creditScore-580)/(850-580)*100;
  const recentTxns=transactions.slice(-5).reverse(),today=new Date(),todayName=DAYS[today.getDay()===0?6:today.getDay()-1];
  const pendKid=(mealSuggestions||[]).filter(s=>s.status==="pending").length+(shopRequests||[]).filter(r=>r.status==="pending").length;
  const upBills=(bills||[]).filter(b=>!billPaid(b)&&Math.ceil((new Date(b.dueDate+"T12:00:00")-today)/(864e5))>=0&&Math.ceil((new Date(b.dueDate+"T12:00:00")-today)/(864e5))<=7).sort((a,c)=>new Date(a.dueDate)-new Date(c.dueDate));
  return(<>
    {dti>40&&<div style={S.alert("#FF9800")}><span style={{color:"#FF9800",fontWeight:"bold"}}>DTI WARNING </span><span style={{color:S.T.sub,fontSize:13}}>DTI is {dti.toFixed(1)}% — close to the 43% limit.</span></div>}
    {profile.pslfMonths<=24&&<div style={S.alert(GOLD)}><span style={{color:GOLD,fontWeight:"bold"}}>PSLF: {profile.pslfMonths} months left — </span><span style={{color:S.T.sub,fontSize:13}}>Don't change IDR plan or leave federal employment.</span></div>}
    {cushion<10000&&<div style={S.alert("#f44336")}><span style={{color:"#f44336",fontWeight:"bold"}}>CUSHION ALERT — </span><span style={{color:S.T.sub,fontSize:13}}>After closing ~{fmt(cushion)} left.</span></div>}
    <div style={S.card}><div style={{display:"flex",justifyContent:"space-around",alignItems:"center",flexWrap:"wrap",gap:16,padding:"6px 0"}}>
      <Ring pct={savProg} color={GOLD} label={`${savProg.toFixed(0)}%`} sub="Savings vs Need"/>
      <Ring pct={ccProg} color="#4CAF50" label={`${ccProg.toFixed(0)}%`} sub="CC Debt Cleared"/>
      <Ring pct={pslfProg} color="#2196F3" label={`${pslfProg.toFixed(0)}%`} sub="PSLF Progress"/>
      <Ring pct={Math.min(dti/43*100,100)} color={dti<36?"#4CAF50":dti<43?"#FF9800":"#f44336"} label={`${dti.toFixed(1)}%`} sub="DTI Ratio"/>
      <Ring pct={scoreProg} color="#9C27B0" label={profile.creditScore} sub="Credit Score"/>
      <Ring pct={Math.min(netWorth/200000*100,100)} color={netWorth>0?GOLD:"#f44336"} label={fmt(netWorth)} sub="Net Worth"/>
    </div></div>
    <div style={S.grid4}>{[{label:"Combined Liquid",val:fmt(combinedLiquid),sub:"Savings available",color:GOLD},{label:"Total CC Debt",val:fmt(totalCC),sub:`${debts.filter(d=>d.type==="Credit Card").length} cards`,color:totalCC>0?"#f44336":"#4CAF50"},{label:"Post-Close Cushion",val:fmt(cushion),sub:"After down+closing+CC",color:cushion>15000?"#4CAF50":cushion>5000?"#FF9800":"#f44336"},{label:"Monthly Surplus",val:fmt(surplus),sub:"After expenses+loans",color:surplus>0?"#4CAF50":"#f44336"}].map((k,i)=><div key={i} style={{...S.card,borderLeft:`3px solid ${k.color}`,marginBottom:0}}><div style={S.label}>{k.label}</div><div style={{fontSize:20,color:k.color,fontWeight:"bold",fontFamily:"monospace"}}>{k.val}</div><div style={{fontSize:11,color:S.T.sub,marginTop:4}}>{k.sub}</div></div>)}</div>
    <div style={S.grid3}>
      <div style={S.card}><div style={S.h2}>Tonight & This Week</div><div style={{fontSize:18,color:GOLD,marginBottom:8}}>{mealPlan[todayName]?.Dinner||"Not planned"}</div>{DAYS.map(d=>{const dinner=mealPlan[d]?.Dinner||"",isToday=d===todayName;return <div key={d} style={{display:"flex",gap:8,padding:"3px 0",borderBottom:`1px solid ${S.T.border}`}}><span style={{fontSize:10,color:isToday?GOLD:S.T.sub,fontFamily:"monospace",minWidth:28}}>{d.slice(0,3)}</span><span style={{fontSize:12,color:dinner?isToday?S.T.text:S.T.sub:"#333"}}>{dinner||"—"}</span></div>;})}<button style={{...S.btnGhost,marginTop:8,fontSize:12}} onClick={()=>setTab("meals")}>Plan Meals →</button></div>
      <div style={S.card}><div style={S.h2}>Expenses Due Soon</div>{upBills.length===0?<div style={{color:S.T.sub,fontSize:13,padding:"8px 0"}}>No expenses due in 7 days</div>:upBills.slice(0,4).map(b=>{const dl=Math.ceil((new Date(b.dueDate+"T12:00:00")-today)/(864e5)),paid=b.bradPaid&&b.maryBethPaid;return(<div key={b.id} style={{...S.row,padding:"6px 0",borderBottom:`1px solid ${S.T.border}`}}><div><div style={{fontSize:13,color:S.T.text}}>{b.name}</div><div style={{fontSize:11,color:S.T.sub}}>{dl===0?"Today":dl===1?"Tomorrow":`${dl} days`}</div></div><div style={{textAlign:"right"}}><div style={{fontFamily:"monospace",color:GOLD,fontWeight:"bold"}}>{fmt(b.amount/2)} ea</div><div style={{fontSize:10,color:paid?"#4CAF50":"#FF9800"}}>{paid?"✓ Paid":"Pending"}</div></div></div>);})} <button style={{...S.btnGhost,marginTop:8,fontSize:12}} onClick={()=>setTab("bills")}>Manage Expenses →</button></div>
      <div style={S.card}><div style={S.h2}>Kids Requests</div>{pendKid===0?<div style={{color:S.T.sub,fontSize:13,padding:"8px 0"}}>No pending requests.</div>:<div style={{...S.alert(GOLD),margin:"0 0 8px"}}><span style={{color:GOLD,fontWeight:"bold"}}>{pendKid} pending</span><span style={{color:S.T.sub,fontSize:12}}> — needs review</span></div>}{(mealSuggestions||[]).filter(s=>s.status==="pending").slice(0,2).map(s=><div key={s.id} style={{padding:"4px 0",borderBottom:`1px solid ${S.T.border}`}}><div style={{fontSize:12,color:S.T.text}}>🍴 {s.meal} <span style={{color:S.T.sub}}>— {s.kidName}</span></div></div>)}{(shopRequests||[]).filter(r=>r.status==="pending").slice(0,2).map(r=><div key={r.id} style={{padding:"4px 0",borderBottom:`1px solid ${S.T.border}`}}><div style={{fontSize:12,color:S.T.text}}>🛒 {r.item} <span style={{color:S.T.sub}}>— {r.kidName}</span></div></div>)}<button style={{...S.btnGhost,marginTop:8,fontSize:12}} onClick={()=>setTab("meals")}>Review →</button></div>
    </div>
    <div style={S.grid2}>
      <div style={S.card}><div style={S.h2}>Monthly Cash Flow</div>{[{label:"Take-Home (~65%)",val:takeHome,color:"#4CAF50",sign:"+"},{label:"Living Expenses",val:totalExpenses,color:"#f44336",sign:"−"},{label:"Student Loan (IDR/PSLF)",val:slPayment,color:"#f44336",sign:"−"},{label:"Future Mortgage",val:monthlyMortgage,color:"#888",sign:"~"}].map((r,i)=><div key={i} style={{...S.row,padding:"6px 0",borderBottom:`1px solid ${S.T.border}`}}><span style={{fontSize:13,color:S.T.sub}}>{r.sign} {r.label}</span><span style={{color:r.color,fontFamily:"monospace",fontWeight:"bold"}}>{fmt(r.val)}</span></div>)}<div style={{...S.row,marginTop:10,paddingTop:10,borderTop:`1px solid ${S.T.border}`}}><span style={{color:GOLD,fontWeight:"bold"}}>Monthly Surplus</span><span style={{color:GOLD,fontFamily:"monospace",fontSize:18,fontWeight:"bold"}}>{fmt(surplus)}</span></div></div>
      <div style={S.card}><div style={S.h2}>Goals Snapshot</div>{goals.map(g=>{const p=Math.min(g.saved/g.target*100,100);return <div key={g.id} style={{marginBottom:10}}><div style={{...S.row,marginBottom:4}}><span style={{fontSize:13,color:S.T.text}}>{g.icon} {g.name}</span><span style={{fontSize:12,color:g.color,fontFamily:"monospace"}}>{fmt(g.saved)} / {fmt(g.target)}</span></div><Bar value={g.saved} max={g.target} color={g.color}/></div>;})}<button style={{...S.btnGhost,marginTop:6,fontSize:12}} onClick={()=>setTab("goals")}>Manage Goals →</button></div>
    </div>
    {recentTxns.length>0&&<div style={S.card}><div style={S.h2}>Recent Transactions</div>{recentTxns.map(t=><div key={t.id} style={{...S.row,padding:"6px 0",borderBottom:`1px solid ${S.T.border}`,flexWrap:"wrap",gap:8}}><div><div style={{fontSize:13,color:S.T.text}}>{t.description}</div><div style={{fontSize:11,color:S.T.sub}}>{t.date} · <span style={S.tag("#888")}>{t.category}</span></div></div><span style={{color:t.amount<0?"#f44336":"#4CAF50",fontFamily:"monospace",fontWeight:"bold"}}>{t.amount<0?"−":"+"}{fmt(Math.abs(t.amount))}</span></div>)}</div>}
  </>);
}

export {
  AcctRow, AccountsTab, DebtsTab, BudgetTab, GoalsTab, StatementsTab,
  ScenariosTab, PslfTab, DashboardTab,
};
